export function createDom() {
  return {
    appRoot: document.getElementById('app-root'),
    graphContainer: document.getElementById('graph-container'),
    inspect: document.getElementById('inspect'),
    selection: document.getElementById('selection'),
    search: document.getElementById('search'),
    pathFromInput: document.getElementById('path-from'),
    pathToInput: document.getElementById('path-to'),
    pathGoBtn: document.getElementById('path-go'),
    pathClearBtn: document.getElementById('path-clear'),
    pathReverseBtn: document.getElementById('path-reverse'),
    pathStatus: document.getElementById('path-status'),
    pathList: document.getElementById('path-list'),
    directedToggle: document.getElementById('directed-toggle'),
    renderEdgeDirectionToggle: document.getElementById('render-edge-direction-toggle'),
    lineNumbersToggle: document.getElementById('line-numbers-toggle'),
    layoutModeSelect: document.getElementById('layout-mode'),
    sizeModeSelect: document.getElementById('node-size-mode'),
    sizeBaseInput: document.getElementById('node-size-base'),
    sizeCodeFactorInput: document.getElementById('node-size-code-factor'),
    sizeBaseValue: document.getElementById('node-size-base-value'),
    sizeCodeFactorValue: document.getElementById('node-size-code-factor-value'),
    mainSourceSelect: document.getElementById('main-source-select'),
    recomputeMainBtn: document.getElementById('recompute-main'),
    transparencyInput: document.getElementById('pane-transparency'),
    transparencyValue: document.getElementById('pane-transparency-value'),
    collapseSidebarBtn: document.getElementById('collapse-sidebar'),
    mainComponentFocusBtn: document.getElementById('main-component-focus'),
    sidebarTabs: document.querySelectorAll('[data-tab-button]'),
    sidebarPanels: document.querySelectorAll('[data-tab-panel]'),
    rightPane: document.getElementById('right-pane'),
    rightPaneWrap: document.getElementById('right-pane-wrap'),
    rightPaneResizeCorner: document.getElementById('right-pane-resize-corner'),
  };
}
